name: App Monitoring Pipeline

on:
  push:
    branches: [ "master" ]
    tags: [ "v*" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  app_monitor_verify-dependencies:
    uses: ./.github/workflows/app_monitor_verify-dependencies.yml

  app_monitor_build-qt:
    needs: app_monitor_verify-dependencies
    uses: ./.github/workflows/app_monitor_build-qt.yml

  app_monitor_build-cli:
    needs: app_monitor_verify-dependencies
    uses: ./.github/workflows/app_monitor_build-cli.yml
  app_monitor_publish:
    needs: [ app_monitor_build-qt, app_monitor_build-cli ]
    uses: ./.github/workflows/app_monitor_publish-artifacts.yml
